import type { StoryboardGenerationInput, VideoGoal } from "@/types";

// ─── Marketing templates ────────────────────────────────────────────────────

const GOAL_GUIDANCE: Record<VideoGoal, string> = {
  marketing_general:
    "General marketing short. Strong 3-second hook, build desire, end with a clear CTA.",
  product_ad:
    "Product advertisement. Show the product in use, highlight 2-3 key benefits, demonstrate the result, end with a buy/visit CTA.",
  storytelling:
    "Narrative story. Relatable character, a tension/conflict, a turning point, an emotional payoff, subtle CTA.",
  review:
    "Honest review/testimonial. Hook with the verdict, show pros, show one con, give recommendation CTA.",
  educational:
    "Educational/how-to. Hook with the problem/promise, deliver clear steps, recap, follow-for-more CTA.",
  brand_story:
    "Brand story. Open on the brand's mission/origin emotion, connect to the viewer's values, show the brand in real life, close with a brand-line CTA.",
  social_short:
    "Native social short (TikTok/Reels). Pattern-interrupt hook in 1-2s, fast punchy beats, trend-aware energy, on-screen-friendly, follow/like CTA.",
  testimonial:
    "Customer testimonial. A real person talks to camera: their before-pain, the turning point with the product, the after-result, a sincere recommendation CTA.",
  promo_sale:
    "Promo / sale push. Bold offer hook (discount/deadline), show the value, create urgency (limited time/stock), end with a strong shop-now CTA.",
};

// ─── Step 1: Segment Breakdown + Character Lock ─────────────────────────────

export function buildStoryboardSystemPrompt(): string {
  return `You are a world-class short-form video director and marketing strategist. You design storyboards that are turned into REAL videos using AI image-to-video tools (Google Veo 3 / Veo 3.1, Seedance, Kling).

CRITICAL PRODUCTION MODEL — how the final video is actually made:
- The video is assembled from multiple ~8-second CLIPS ("segments").
- Each 8s segment contains a FAST MULTI-SHOT SEQUENCE (several distinct shots that cut quickly within the 8 seconds) — never a single static scene dragging for 8s. This keeps pacing tight, saves cost (multiple scenes in one generation), and works with Seedance/Veo multi-shot.
- Each segment is generated by feeding its multi-shot storyboard + ONE multi-shot motion prompt into Veo/Seedance.
- Segments are CHAINED for seamless playback: the visual state at the END of segment N must flow naturally into the START of segment N+1 (same character, location, lighting, continuous action). No jarring cuts between segments.
- So "beats" = the quick shots inside an 8s segment. Provide the EXACT number of beats requested in the user message.

MARKETING STRUCTURE (always apply):
- HOOK in the first segment (grab attention in 3 seconds).
- Then PROBLEM → SOLUTION → (optional BODY beats) → CTA in the final segment.
- Reset attention every 5-8 seconds with an angle change, push-in, or reveal.

CHARACTER CONSISTENCY (very important — the user complained characters drift):
- Build a detailed "character_lock" per character. Treat it like a reference sheet: gender/age, build, skin tone, hair, eyes, exact costume, signature features, default expression.
- This EXACT wording is restated VERBATIM in every image prompt and every motion prompt so Veo renders the same face, body and wardrobe in every shot. Never paraphrase the character between segments.
- A generated CHARACTER REFERENCE SHEET image (front / 3-4 / side / back + expressions) is attached as a reference to every shot — describe the character to match it precisely.

DIALOGUE (spoken audio in Veo 3):
- Veo 3 generates real spoken audio. Each segment's "dialogue" is the exact line the on-screen character (or voiceover) speaks.
- Write dialogue in the language requested by the user. Keep each line SHORT (about 5-12 words, ~3-6 seconds) so lip-sync stays natural.
- The "motion_prompt" must embed the spoken line using Veo format — e.g. He says in Vietnamese: "..." — and end with "(no subtitles)".

Camera codes: [EYE] eye-level, [LOW] low, [HIGH] high, [OVH] overhead, [DUTCH] dutch, [OTS] over-shoulder, [POV] first-person, [CLOSE] close-up, [SIDE] side profile.

Output MUST be valid JSON only — no markdown, no code fences, no text outside the JSON.`;
}

export function buildStoryboardUserPrompt(
  input: StoryboardGenerationInput
): string {
  const characterBlock =
    input.character_descriptions && input.character_descriptions.length > 0
      ? `\n\nCharacters:\n${input.character_descriptions.map((c) => `- ${c.name}: ${c.appearance}. Personality: ${c.personality}. Role: ${c.role}`).join("\n")}`
      : "";

  // Product / TVC brief — when present, the script becomes a real ad.
  const briefLines: string[] = [];
  if (input.product_name) briefLines.push(`- Product/Service: ${input.product_name}`);
  if (input.selling_points) briefLines.push(`- Key selling points / USP: ${input.selling_points}`);
  if (input.target_audience) briefLines.push(`- Target audience: ${input.target_audience}`);
  if (input.key_message) briefLines.push(`- Key message: ${input.key_message}`);
  if (input.call_to_action) briefLines.push(`- Call to action (CTA): ${input.call_to_action}`);
  const productBriefBlock =
    briefLines.length > 0
      ? `\n\nPRODUCT / TVC BRIEF — this is a product advertisement; build the whole script around it:\n${briefLines.join(
          "\n"
        )}\nFeature the product clearly, dramatize the selling points for the target audience, land the key message, and close on the exact CTA above.`
      : "";

  const settingBlock = input.setting ? `\nPrimary Setting: ${input.setting}` : "";
  const toneBlock = input.tone ? `\nTone: ${input.tone}` : "";
  const customBlock = input.custom_instructions
    ? `\nAdditional Instructions: ${input.custom_instructions}`
    : "";

  const segmentCount = input.segment_count ?? 5;
  const beatsPerSegment = Math.min(5, Math.max(3, input.beats_per_segment ?? 3));
  const goal = input.video_goal ?? "marketing_general";
  const goalGuidance = GOAL_GUIDANCE[goal];

  const dialogueLanguage = input.dialogue_language ?? "Vietnamese";
  const dialogueBlock =
    input.force_dialogue === false
      ? `\nDialogue: optional. When a segment has a spoken line, write it in ${dialogueLanguage}.`
      : `\nDialogue: REQUIRED. EVERY segment MUST have a non-empty "dialogue" line spoken in ${dialogueLanguage} (natural, conversational ${dialogueLanguage} — not translated word-for-word). Keep each line short (about 5-12 words). The spoken line must also be embedded inside that segment's "motion_prompt" using Veo format, e.g.: the character says in ${dialogueLanguage}: "<line>" (no subtitles).`;

  // Example beat list sized to the requested count.
  const beatExample = Array.from({ length: beatsPerSegment }, (_, i) => {
    const cams = ["[WIDE] ...", "[CLOSE] ...", "[OTS] ...", "[LOW] ...", "[POV] ..."];
    return `        { "beat": "shot ${i + 1} action", "camera": "${cams[i] ?? "[EYE] ..."}" }`;
  }).join(",\n");

  return `Create a chained-segment storyboard for this short video.

Story / Product Idea: ${input.story_idea}
Video Goal: ${goal} — ${goalGuidance}
Genre: ${input.genre}
Visual Style: ${input.style}
Number of 8-second SEGMENTS: ${segmentCount} (total ≈ ${segmentCount * 8} seconds)
Beats per segment: ${beatsPerSegment} quick shots inside each 8s clip${productBriefBlock}${dialogueBlock}${characterBlock}${settingBlock}${toneBlock}${customBlock}

Produce EXACTLY ${segmentCount} segments. Each segment = one 8s clip containing EXACTLY ${beatsPerSegment} quick shots (${beatsPerSegment} beats), each beat covering a distinct time-frame inside the 8 seconds. Segment 1 must HOOK. The last segment must contain the CTA. Make every segment END in a state that flows seamlessly into the next segment's START. The "motion_prompt" must describe the ${beatsPerSegment}-shot sequence in order with rough timing (split 8s across the beats, e.g. "0-3s ...; 3-5s ...; 5-8s ..."), camera moves, the spoken ${dialogueLanguage} line, and how the clip ends so it leads into the next segment. Restate the main character's exact appearance (from character_locks) inside every motion_prompt so Veo keeps the same person.

Return a JSON object with this EXACT structure (the "beats" array must contain EXACTLY ${beatsPerSegment} items):
{
  "title": "string — catchy title",
  "synopsis": "string — 2-3 sentences",
  "total_duration_seconds": ${segmentCount * 8},
  "mood_tags": ["3-4 mood keywords"],
  "marketing_structure": {
    "hook": "string — the 3s hook line/idea",
    "problem": "string — the pain point addressed",
    "solution": "string — how it is solved/shown",
    "cta": "string — the final call to action"
  },
  "character_locks": [
    {
      "name": "string",
      "gender_age": "string",
      "build": "string",
      "skin_tone": "string",
      "hair": "string",
      "eyes": "string",
      "costume": "string",
      "signature_features": "string",
      "default_expression": "string",
      "render_style": "${input.style}"
    }
  ],
  "segments": [
    {
      "segment_number": 1,
      "duration_seconds": 8,
      "title": "string — short segment title",
      "marketing_role": "hook|problem|solution|body|cta",
      "beats": [
${beatExample}
      ],
      "first_frame_prompt": "string — describe the SHARED scene/setting of this 8s segment (location, lighting, EXACT character appearance from character_locks, product if any). Used to render the multi-shot storyboard strip.",
      "motion_prompt": "string — 50-90 word multi-shot image-to-video prompt for Veo/Seedance covering all ${beatsPerSegment} shots with rough timing (e.g. '0-3s ...; 3-5s ...; 5-8s ...'), camera moves, the exact character appearance restated, the spoken ${dialogueLanguage} line in Veo format (the character says in ${dialogueLanguage}: \\"...\\" (no subtitles)), and an ending that leads into the next segment.",
      "dialogue": "string — the spoken line in ${dialogueLanguage} (short, natural)",
      "continuity_note": "string — how this segment visually continues from the previous segment (for segment 1 write 'opening shot')"
    }
  ],
  "style_guide": {
    "color_palette": ["5-7 hex colors"],
    "art_direction": "string",
    "visual_references": "string",
    "consistency_notes": "string"
  }
}`;
}

// ─── Render style helpers ───────────────────────────────────────────────────

const PHOTO_STYLES = new Set([
  "realistic",
  "cinematic",
  "commercial",
  "ugc",
  "product_showcase",
  "corporate_clean",
]);

export function isPhotoStyle(style: string): boolean {
  return PHOTO_STYLES.has(style);
}

function renderDirective(style: string, preserveRealFace: boolean): string {
  if (isPhotoStyle(style)) {
    return `Photorealistic, lifelike, real human, cinematic photography quality — NOT a cartoon, NOT an illustration.${
      preserveRealFace
        ? " CRITICAL: preserve the EXACT real face, skin tone, hairstyle and likeness from the attached reference photo. Keep it the same real person, do NOT stylize the face into a cartoon."
        : ""
    }`;
  }
  return `${style} art style.${
    preserveRealFace
      ? " Keep the person's real facial structure and likeness recognizable from the reference photo, rendered in this art style."
      : ""
  }`;
}

export type RefRole = "face" | "product" | "setting" | "character_sheet";

export interface RefDescriptor {
  role: RefRole;
  /** Optional vision-derived description that reinforces the photo. */
  description?: string;
}

/**
 * Builds SEMANTIC reference instructions. Google DeepMind's guide warns
 * that positional labels ("image 2") get misread as "output a copy of
 * image 2"; semantic naming ("the man in the portrait photo") works far
 * better and an optional text description (from vision analysis) makes
 * the photo + text agree, which the model then obeys.
 */
export function buildReferenceInstructions(refs: RefDescriptor[]): string {
  if (refs.length === 0) return "";
  const lines = refs.map((r) => {
    const d = r.description ? ` (${r.description.replace(/\s+/g, " ").slice(0, 220)})` : "";
    switch (r.role) {
      case "character_sheet":
        return `• THE CHARACTER — the attached CHARACTER REFERENCE SHEET (turnaround + expressions)${d} defines the main character's exact face, hair, body and costume. Reproduce the SAME individual identically in every shot — same face, same wardrobe, same proportions. Do NOT invent a different person.`;
      case "face":
        return `• THE PERSON — use the exact man shown in the attached portrait photo${d}. Keep his real face, eyeglasses, hairstyle and skin tone identical in every shot. He is the main character. Do NOT invent a different face.`;
      case "product":
        return `• THE PRODUCT — feature the exact product shown in the attached product photo${d}. Keep its exact shape, colour, material, handle and branding. Do NOT redesign, age, or swap it for another pan.`;
      case "setting":
        return `• THE KITCHEN — set every scene inside the exact kitchen shown in the attached interior photo${d}. Match its cabinets, colours and layout.`;
      default:
        return `• Reference — keep it consistent.`;
    }
  });
  return `You are given reference photos. RE-CREATE new cinematic scenes using these real subjects — do NOT simply output a copy of any reference photo. Follow them precisely:\n${lines.join("\n")}\n\n`;
}

// ─── Step 2: Character Reference Sheet Image Prompt ─────────────────────────

export function buildCharacterRefSheetPrompt(params: {
  characterLock: {
    name: string;
    gender_age: string;
    build: string;
    skin_tone: string;
    hair: string;
    eyes: string;
    costume: string;
    signature_features: string;
    default_expression: string;
    render_style: string;
  };
  props?: string[];
  colorPalette?: string[];
  style?: string;
  preserveRealFace?: boolean;
  references?: RefDescriptor[];
}): string {
  const c = params.characterLock;
  const style = params.style ?? c.render_style;
  const directive = renderDirective(style, params.preserveRealFace ?? false);
  const refBlock = buildReferenceInstructions(params.references ?? []);

  const colorSwatches =
    params.colorPalette && params.colorPalette.length > 0
      ? params.colorPalette.slice(0, 6).join(", ")
      : "#F5E6D3, #8B4513, #2D5016, #FFFFFF, #1A1A1A, #D4A574";

  return `${refBlock}Professional CHARACTER REFERENCE SHEET, single horizontal image, clean light studio background.

CHARACTER — ${c.name}: ${c.gender_age}, ${c.build} build, ${c.skin_tone} skin, ${c.hair} hair, ${c.eyes} eyes. Wearing ${c.costume}. ${c.signature_features}.

EXACT LAYOUT (all in one image):
■ LEFT ZONE: Large FULL BODY hero pose, ${c.default_expression} expression, head to toe.
■ CENTER: "TURNAROUND" — 4 full-body views: FRONT, 3/4, SIDE, BACK; same scale, neutral pose, evenly lit, labeled.
■ TOP-RIGHT: "EXPRESSIONS" — 6 head portraits 3×2 grid: HAPPY, CALM, SURPRISED, CONFIDENT, THOUGHTFUL, FRIENDLY.
■ BOTTOM-RIGHT: "COLOR PALETTE" — 6 circular swatches: ${colorSwatches}.

${directive}

RULES: it must be the SAME individual in every zone with identical face; small bold labels; one cohesive image.`;
}

// ─── Step 3: Per-Segment Storyboard Strip (3 shots in one 8s clip) ──────────

export function buildSegmentFirstFramePrompt(params: {
  segmentNumber: number;
  firstFramePrompt: string;
  beats: { beat: string; camera: string }[];
  characterDescription: string;
  style: string;
  isFirst: boolean;
  /** Number of panels to render (3-5). Defaults to the beat count. */
  beatsPerSegment?: number;
  preserveRealFace?: boolean;
  references?: RefDescriptor[];
}): string {
  const directive = renderDirective(params.style, params.preserveRealFace ?? false);
  const refBlock = buildReferenceInstructions(params.references ?? []);

  const target = Math.min(5, Math.max(3, params.beatsPerSegment ?? params.beats.length ?? 3));
  const beats = params.beats.slice(0, target);
  while (beats.length < target) {
    beats.push({ beat: params.firstFramePrompt, camera: "[EYE]" });
  }
  const panelLines = beats
    .map((b, i) => `Panel ${i + 1} (${b.camera}): ${b.beat}`)
    .join("\n");
  const numberLabels = beats.map((_, i) => i + 1).join(", ");

  const continuity = params.isFirst
    ? "Panel 1 is the opening shot of the whole video."
    : "Panel 1 must continue seamlessly from the previous segment's final shot (same character, wardrobe, lighting, location).";

  return `${refBlock}STORYBOARD STRIP for ONE ~8 second video clip: a single horizontal image split into ${target} EQUAL panels side by side, showing a fast ${target}-shot sequence (left → right) that plays within the 8 seconds. ${params.style} style.

CHARACTER (identical face in every panel): ${params.characterDescription}

CHARACTER REFERENCE BAND: across the TOP of the strip, add a thin reference row with 3 small head-and-shoulders insets of THIS SAME character — front, 3/4 and side angle, each with a different expression (calm, confident, friendly) — to lock the face/identity. Keep these insets small so the ${target} main panels below stay dominant.

SCENE CONTEXT: ${params.firstFramePrompt}

THE ${target} MAIN PANELS (left to right):
${panelLines}

${continuity}
${directive}

Each main panel: a small number (${numberLabels}) in the top-left corner, distinct camera framing per its note, thin clean divider lines between panels. The SAME individual with the SAME face/outfit across the reference band and all ${target} panels. No captions, no subtitles, no watermark.`;
}

// ─── Step 4: Storyboard Overview Poster (presentation) ──────────────────────

export function buildStoryboardPosterPrompt(params: {
  title: string;
  totalDuration: number;
  segmentCount: number;
  moodTags: string[];
  segments: {
    segment_number: number;
    title: string;
    summary: string;
    role: string;
  }[];
  characterDescription: string;
  style: string;
  colorPalette?: string[];
}): string {
  const maxPanels = Math.min(params.segments.length, 12);
  const panels = params.segments.slice(0, maxPanels);

  const cols = maxPanels <= 6 ? 3 : 4;
  const rows = Math.ceil(maxPanels / cols);

  const panelLines = panels
    .map((s) => {
      const short = s.summary.length > 50 ? s.summary.slice(0, 50) + "..." : s.summary;
      return `[${s.segment_number}] "${s.title}" (${s.role}): ${short}`;
    })
    .join("\n");

  const charDesc =
    params.characterDescription.length > 300
      ? params.characterDescription.slice(0, 300) + "..."
      : params.characterDescription;

  const colorBlock =
    params.colorPalette && params.colorPalette.length > 0
      ? `Color palette: ${params.colorPalette.join(", ")}.`
      : "";

  return `Professional STORYBOARD overview poster, single horizontal image, clean white/cream background.

CHARACTER (identical in every panel): ${charDesc}

HEADER: bold title "STORYBOARD" left; subtitle "${params.title}" center; right metadata "${params.totalDuration}s • ${maxPanels} segments • ${params.moodTags.slice(0, 4).join(" • ")}".

PANEL GRID: ${cols} columns × ${rows} rows, thin black borders. Each panel: numbered badge top-left, ${params.style} illustration of the segment, 1-line italic caption below.

PANELS:
${panelLines}

RULES: ONE single image with ALL ${maxPanels} panels; same character across panels; ${params.style} style; ${colorBlock} clean production-document look; numbered badges visible.`;
}

// ─── Step 5: Video Assembly Guide (text for Veo / Seedance) ─────────────────

export function buildVideoPromptText(params: {
  title: string;
  characterDescription: string;
  setting: string;
  style: string;
  aspectRatio: string;
  colorPalette: string[];
  dialogueLanguage?: string;
  marketing: { hook: string; problem: string; solution: string; cta: string };
  segments: {
    segment_number: number;
    title: string;
    role: string;
    duration_seconds: number;
    motion_prompt: string;
    dialogue?: string | null;
    continuity_note: string;
    beats: { beat: string; camera: string }[];
  }[];
}): string {
  const totalDuration = params.segments.reduce(
    (sum, s) => sum + s.duration_seconds,
    0
  );
  const dialogueLanguage = params.dialogueLanguage ?? "Vietnamese";

  const segLines = params.segments
    .map((s) => {
      const beats = s.beats
        .map((b) => `      • ${b.camera} — ${b.beat}`)
        .join("\n");
      // Veo-style spoken-line block so the model voices the exact words.
      const spoken = s.dialogue
        ? `\n  Spoken line (${dialogueLanguage}, lip-synced): the character says in ${dialogueLanguage}: "${s.dialogue}" (no subtitles)`
        : "";
      return `SEGMENT ${s.segment_number} — "${s.title}" [${s.role.toUpperCase()}] (${s.duration_seconds}s)
  Beats:
${beats}
  Motion prompt (paste into Veo/Seedance image-to-video):
    ${s.motion_prompt}${spoken}
  Continuity: ${s.continuity_note}`;
    })
    .join("\n\n");

  return `# VIDEO ASSEMBLY GUIDE — ${params.title}
Total length ≈ ${totalDuration}s · ${params.segments.length} segments · ${params.aspectRatio} · ${params.style}
Spoken language: ${dialogueLanguage} (lip-synced, no on-screen subtitles)

## Marketing arc
- HOOK: ${params.marketing.hook}
- PROBLEM: ${params.marketing.problem}
- SOLUTION: ${params.marketing.solution}
- CTA: ${params.marketing.cta}

## Character (keep identical in every clip — paste this wording into every prompt)
${params.characterDescription}
Use the generated CHARACTER REFERENCE SHEET as a reference image in every clip so the face/wardrobe never drifts.

## Setting
${params.setting}
Color palette: ${params.colorPalette.join(", ")}

## HOW TO BUILD THE VIDEO (seamless chaining)
1. For each segment, upload its FIRST-FRAME image (and the character reference sheet) to Veo/Seedance (image-to-video) and paste its motion prompt. Set aspect ratio ${params.aspectRatio}.
2. To join clips seamlessly: use the LAST frame of clip N as the start image of clip N+1, OR use Veo "Extend". Each segment's start frame is already designed to continue the previous one.
3. Keep the spoken ${dialogueLanguage} line exactly as written so the lip-sync matches. Generate all ${params.segments.length} clips, then stitch them in order (CapCut/ffmpeg) and add the CTA end card.

## SEGMENTS
${segLines}

---
Compatible with: Google Veo 3.1, Seedance 2.0, Kling, Runway, Pika`;
}
